In [1]:
import numpy as np

In [2]:
a = np.array(range(10), dtype=float)

print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [3]:
a = np.empty(5)

print(a)

[6.93394969e-310 6.93394968e-310 6.93394630e-310 6.93394960e-310
 6.93393976e-310]


In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
m = np.eye(5, dtype=int)

print(m)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
m.ndim, m.shape, m.size, m.dtype

(2, (5, 5), 25, dtype('int64'))

In [7]:
a = np.arange(5)
b = np.arange(5, 0, -1)

a, b, a-b, a @ b

(array([0, 1, 2, 3, 4]),
 array([5, 4, 3, 2, 1]),
 array([-5, -3, -1,  1,  3]),
 20)

In [8]:
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(np.arange(16).reshape(4, 4)**2, index=list("abcd"), columns=list("ABCD"))
df

A    B    C    D
a    0    1    4    9
b   16   25   36   49
c   64   81  100  121
d  144  169  196  225